//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BramkiUsers.SystemSynchronization
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.roger.pl/systemsynchronization", ConfigurationName="BramkiUsers.SystemSynchronization.ISystemSynchronizationService")]
    public interface ISystemSynchronizationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/systemsynchronization/ISystemSynchronizationService/PartialCr" +
            "edentialSynchronization", ReplyAction="http://www.roger.pl/systemsynchronization/ISystemSynchronizationService/PartialCr" +
            "edentialSynchronizationResponse")]
        System.Threading.Tasks.Task<int> PartialCredentialSynchronizationAsync(int credentialId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/systemsynchronization/ISystemSynchronizationService/PartialCr" +
            "edentialsSynchronization", ReplyAction="http://www.roger.pl/systemsynchronization/ISystemSynchronizationService/PartialCr" +
            "edentialsSynchronizationResponse")]
        System.Threading.Tasks.Task<int> PartialCredentialsSynchronizationAsync(int[] credentialIds, System.Guid sessionToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISystemSynchronizationServiceChannel : BramkiUsers.SystemSynchronization.ISystemSynchronizationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SystemSynchronizationServiceClient : System.ServiceModel.ClientBase<BramkiUsers.SystemSynchronization.ISystemSynchronizationService>, BramkiUsers.SystemSynchronization.ISystemSynchronizationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SystemSynchronizationServiceClient() : 
                base(SystemSynchronizationServiceClient.GetDefaultBinding(), SystemSynchronizationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISystemSynchronizationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SystemSynchronizationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SystemSynchronizationServiceClient.GetBindingForEndpoint(endpointConfiguration), SystemSynchronizationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SystemSynchronizationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SystemSynchronizationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SystemSynchronizationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SystemSynchronizationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SystemSynchronizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> PartialCredentialSynchronizationAsync(int credentialId, System.Guid sessionToken)
        {
            return base.Channel.PartialCredentialSynchronizationAsync(credentialId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> PartialCredentialsSynchronizationAsync(int[] credentialIds, System.Guid sessionToken)
        {
            return base.Channel.PartialCredentialsSynchronizationAsync(credentialIds, sessionToken);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISystemSynchronizationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISystemSynchronizationService))
            {
                return new System.ServiceModel.EndpointAddress("http://127.0.0.1:8892/SystemSynchronization");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SystemSynchronizationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISystemSynchronizationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SystemSynchronizationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISystemSynchronizationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISystemSynchronizationService,
        }
    }
}
