//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BramkiUsers.Integration
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class PersonData : BramkiUsers.Integration.BaseData
    {
        
        private string AddressField;
        
        private string CityField;
        
        private decimal CreditField;
        
        private BramkiUsers.Integration.AccessUserCustomFieldValueData[] CustomFieldValuesField;
        
        private string DataAccessibleForField;
        
        private bool DataProcessingPermissionField;
        
        private System.Nullable<int> DefaultCredentialIDField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private System.Nullable<int> GlobalIDField;
        
        private System.Nullable<int> GroupIDField;
        
        private string GroupNameField;
        
        private string LastNameField;
        
        private System.Nullable<int> OperatorIDField;
        
        private string PhoneField;
        
        private byte[] PhotoField;
        
        private string PostalCodeField;
        
        private string UserExternalIdentifierField;
        
        private string UserInformationReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AddressField, value) != true))
                {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CityField, value) != true))
                {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Credit
        {
            get
            {
                return this.CreditField;
            }
            set
            {
                if ((this.CreditField.Equals(value) != true))
                {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BramkiUsers.Integration.AccessUserCustomFieldValueData[] CustomFieldValues
        {
            get
            {
                return this.CustomFieldValuesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomFieldValuesField, value) != true))
                {
                    this.CustomFieldValuesField = value;
                    this.RaisePropertyChanged("CustomFieldValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataAccessibleFor
        {
            get
            {
                return this.DataAccessibleForField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DataAccessibleForField, value) != true))
                {
                    this.DataAccessibleForField = value;
                    this.RaisePropertyChanged("DataAccessibleFor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DataProcessingPermission
        {
            get
            {
                return this.DataProcessingPermissionField;
            }
            set
            {
                if ((this.DataProcessingPermissionField.Equals(value) != true))
                {
                    this.DataProcessingPermissionField = value;
                    this.RaisePropertyChanged("DataProcessingPermission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DefaultCredentialID
        {
            get
            {
                return this.DefaultCredentialIDField;
            }
            set
            {
                if ((this.DefaultCredentialIDField.Equals(value) != true))
                {
                    this.DefaultCredentialIDField = value;
                    this.RaisePropertyChanged("DefaultCredentialID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmailField, value) != true))
                {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true))
                {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GlobalID
        {
            get
            {
                return this.GlobalIDField;
            }
            set
            {
                if ((this.GlobalIDField.Equals(value) != true))
                {
                    this.GlobalIDField = value;
                    this.RaisePropertyChanged("GlobalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GroupID
        {
            get
            {
                return this.GroupIDField;
            }
            set
            {
                if ((this.GroupIDField.Equals(value) != true))
                {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true))
                {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LastNameField, value) != true))
                {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OperatorID
        {
            get
            {
                return this.OperatorIDField;
            }
            set
            {
                if ((this.OperatorIDField.Equals(value) != true))
                {
                    this.OperatorIDField = value;
                    this.RaisePropertyChanged("OperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PhoneField, value) != true))
                {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PhotoField, value) != true))
                {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true))
                {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserExternalIdentifier
        {
            get
            {
                return this.UserExternalIdentifierField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UserExternalIdentifierField, value) != true))
                {
                    this.UserExternalIdentifierField = value;
                    this.RaisePropertyChanged("UserExternalIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserInformationReference
        {
            get
            {
                return this.UserInformationReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UserInformationReferenceField, value) != true))
                {
                    this.UserInformationReferenceField = value;
                    this.RaisePropertyChanged("UserInformationReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BramkiUsers.Integration.PersonData))]
    public partial class BaseData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool DeletedField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private string NameField;
        
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                if ((this.DeletedField.Equals(value) != true))
                {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true))
                {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                return this.UpdatedDateField;
            }
            set
            {
                if ((this.UpdatedDateField.Equals(value) != true))
                {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessUserCustomFieldValueData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class AccessUserCustomFieldValueData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string CustomFieldDefinitionNameField;
        
        private int DefinitionIDField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomFieldDefinitionName
        {
            get
            {
                return this.CustomFieldDefinitionNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomFieldDefinitionNameField, value) != true))
                {
                    this.CustomFieldDefinitionNameField = value;
                    this.RaisePropertyChanged("CustomFieldDefinitionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DefinitionID
        {
            get
            {
                return this.DefinitionIDField;
            }
            set
            {
                if ((this.DefinitionIDField.Equals(value) != true))
                {
                    this.DefinitionIDField = value;
                    this.RaisePropertyChanged("DefinitionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ValueField, value) != true))
                {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class AccessData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.DateTime DateTimeField;
        
        private int ObjectIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                if ((this.DateTimeField.Equals(value) != true))
                {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ObjectID
        {
            get
            {
                return this.ObjectIDField;
            }
            set
            {
                if ((this.ObjectIDField.Equals(value) != true))
                {
                    this.ObjectIDField = value;
                    this.RaisePropertyChanged("ObjectID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.roger.pl/integration", ConfigurationName="BramkiUsers.Integration.IIntegrationService")]
    public interface IIntegrationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/integration/IIntegrationService/RegisterVisitor", ReplyAction="http://www.roger.pl/integration/IIntegrationService/RegisterVisitorResponse")]
        System.Threading.Tasks.Task<int> RegisterVisitorAsync(System.Guid sessionToken, string firstName, string lastName, bool clearExistingPermissionsToRoom, int roomId, int[] permissions, System.DateTime from, System.DateTime to, string cardCode, int callType, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/integration/IIntegrationService/RegisterVisitorWithoutSynchro" +
            "nization", ReplyAction="http://www.roger.pl/integration/IIntegrationService/RegisterVisitorWithoutSynchro" +
            "nizationResponse")]
        System.Threading.Tasks.Task<int> RegisterVisitorWithoutSynchronizationAsync(System.Guid sessionToken, string firstName, string lastName, bool clearExistingPermissionsToRoom, int roomId, int[] permissions, System.DateTime from, System.DateTime to, string cardCode, int callType, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/integration/IIntegrationService/DisableCredential", ReplyAction="http://www.roger.pl/integration/IIntegrationService/DisableCredentialResponse")]
        System.Threading.Tasks.Task<int> DisableCredentialAsync(System.Guid sessionToken, string cardCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/integration/IIntegrationService/SynchronizePendingChanges", ReplyAction="http://www.roger.pl/integration/IIntegrationService/SynchronizePendingChangesResp" +
            "onse")]
        System.Threading.Tasks.Task<int> SynchronizePendingChangesAsync(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/integration/IIntegrationService/GetAttendanceZoneOccupancy", ReplyAction="http://www.roger.pl/integration/IIntegrationService/GetAttendanceZoneOccupancyRes" +
            "ponse")]
        System.Threading.Tasks.Task<int> GetAttendanceZoneOccupancyAsync(int attendanceZoneId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/integration/IIntegrationService/GetAttendanceZoneOccupancies", ReplyAction="http://www.roger.pl/integration/IIntegrationService/GetAttendanceZoneOccupanciesR" +
            "esponse")]
        System.Threading.Tasks.Task<BramkiUsers.Integration.PersonData[]> GetAttendanceZoneOccupanciesAsync(int attendanceZoneId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/integration/IIntegrationService/GetPersonsLoggedOutsideAttend" +
            "anceZone", ReplyAction="http://www.roger.pl/integration/IIntegrationService/GetPersonsLoggedOutsideAttend" +
            "anceZoneResponse")]
        System.Threading.Tasks.Task<BramkiUsers.Integration.PersonData[]> GetPersonsLoggedOutsideAttendanceZoneAsync(int attendanceZoneId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/integration/IIntegrationService/GetAccessZoneOccupancy", ReplyAction="http://www.roger.pl/integration/IIntegrationService/GetAccessZoneOccupancyRespons" +
            "e")]
        System.Threading.Tasks.Task<int> GetAccessZoneOccupancyAsync(int accessZoneId, int monitoringTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/integration/IIntegrationService/GetPersonLastAccessPoint", ReplyAction="http://www.roger.pl/integration/IIntegrationService/GetPersonLastAccessPointRespo" +
            "nse")]
        System.Threading.Tasks.Task<BramkiUsers.Integration.AccessData> GetPersonLastAccessPointAsync(int personId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/integration/IIntegrationService/GetAssetLastAccessPoint", ReplyAction="http://www.roger.pl/integration/IIntegrationService/GetAssetLastAccessPointRespon" +
            "se")]
        System.Threading.Tasks.Task<BramkiUsers.Integration.AccessData> GetAssetLastAccessPointAsync(int assetId, System.Guid sessionToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IIntegrationServiceChannel : BramkiUsers.Integration.IIntegrationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class IntegrationServiceClient : System.ServiceModel.ClientBase<BramkiUsers.Integration.IIntegrationService>, BramkiUsers.Integration.IIntegrationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IntegrationServiceClient() : 
                base(IntegrationServiceClient.GetDefaultBinding(), IntegrationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IIntegrationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(IntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), IntegrationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> RegisterVisitorAsync(System.Guid sessionToken, string firstName, string lastName, bool clearExistingPermissionsToRoom, int roomId, int[] permissions, System.DateTime from, System.DateTime to, string cardCode, int callType, int groupId)
        {
            return base.Channel.RegisterVisitorAsync(sessionToken, firstName, lastName, clearExistingPermissionsToRoom, roomId, permissions, from, to, cardCode, callType, groupId);
        }
        
        public System.Threading.Tasks.Task<int> RegisterVisitorWithoutSynchronizationAsync(System.Guid sessionToken, string firstName, string lastName, bool clearExistingPermissionsToRoom, int roomId, int[] permissions, System.DateTime from, System.DateTime to, string cardCode, int callType, int groupId)
        {
            return base.Channel.RegisterVisitorWithoutSynchronizationAsync(sessionToken, firstName, lastName, clearExistingPermissionsToRoom, roomId, permissions, from, to, cardCode, callType, groupId);
        }
        
        public System.Threading.Tasks.Task<int> DisableCredentialAsync(System.Guid sessionToken, string cardCode)
        {
            return base.Channel.DisableCredentialAsync(sessionToken, cardCode);
        }
        
        public System.Threading.Tasks.Task<int> SynchronizePendingChangesAsync(System.Guid sessionToken)
        {
            return base.Channel.SynchronizePendingChangesAsync(sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> GetAttendanceZoneOccupancyAsync(int attendanceZoneId, System.Guid sessionToken)
        {
            return base.Channel.GetAttendanceZoneOccupancyAsync(attendanceZoneId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<BramkiUsers.Integration.PersonData[]> GetAttendanceZoneOccupanciesAsync(int attendanceZoneId, System.Guid sessionToken)
        {
            return base.Channel.GetAttendanceZoneOccupanciesAsync(attendanceZoneId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<BramkiUsers.Integration.PersonData[]> GetPersonsLoggedOutsideAttendanceZoneAsync(int attendanceZoneId, System.Guid sessionToken)
        {
            return base.Channel.GetPersonsLoggedOutsideAttendanceZoneAsync(attendanceZoneId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> GetAccessZoneOccupancyAsync(int accessZoneId, int monitoringTime, System.Guid sessionToken)
        {
            return base.Channel.GetAccessZoneOccupancyAsync(accessZoneId, monitoringTime, sessionToken);
        }
        
        public System.Threading.Tasks.Task<BramkiUsers.Integration.AccessData> GetPersonLastAccessPointAsync(int personId, System.Guid sessionToken)
        {
            return base.Channel.GetPersonLastAccessPointAsync(personId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<BramkiUsers.Integration.AccessData> GetAssetLastAccessPointAsync(int assetId, System.Guid sessionToken)
        {
            return base.Channel.GetAssetLastAccessPointAsync(assetId, sessionToken);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIntegrationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIntegrationService))
            {
                return new System.ServiceModel.EndpointAddress("http://127.0.0.1:8892/Integration");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IntegrationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IIntegrationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IntegrationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IIntegrationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IIntegrationService,
        }
    }
}
