//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BramkiUsers.SessionManagement
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BramkiUsers.SessionManagement.OperatorData))]
    public partial class BaseData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool DeletedField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private string NameField;
        
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                if ((this.DeletedField.Equals(value) != true))
                {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true))
                {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                return this.UpdatedDateField;
            }
            set
            {
                if ((this.UpdatedDateField.Equals(value) != true))
                {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatorData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class OperatorData : BramkiUsers.SessionManagement.BaseData
    {
        
        private int ActiveAuthenticationModeField;
        
        private string DomainNameField;
        
        private string EmailField;
        
        private bool IsInBuildField;
        
        private string LoginField;
        
        private string OrganizationNameField;
        
        private string PasswordField;
        
        private string PhoneField;
        
        private string[] RolesField;
        
        private string SaltField;
        
        private int ScopeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveAuthenticationMode
        {
            get
            {
                return this.ActiveAuthenticationModeField;
            }
            set
            {
                if ((this.ActiveAuthenticationModeField.Equals(value) != true))
                {
                    this.ActiveAuthenticationModeField = value;
                    this.RaisePropertyChanged("ActiveAuthenticationMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DomainName
        {
            get
            {
                return this.DomainNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DomainNameField, value) != true))
                {
                    this.DomainNameField = value;
                    this.RaisePropertyChanged("DomainName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmailField, value) != true))
                {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInBuild
        {
            get
            {
                return this.IsInBuildField;
            }
            set
            {
                if ((this.IsInBuildField.Equals(value) != true))
                {
                    this.IsInBuildField = value;
                    this.RaisePropertyChanged("IsInBuild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LoginField, value) != true))
                {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationName
        {
            get
            {
                return this.OrganizationNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true))
                {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PasswordField, value) != true))
                {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PhoneField, value) != true))
                {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RolesField, value) != true))
                {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salt
        {
            get
            {
                return this.SaltField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SaltField, value) != true))
                {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Scope
        {
            get
            {
                return this.ScopeField;
            }
            set
            {
                if ((this.ScopeField.Equals(value) != true))
                {
                    this.ScopeField = value;
                    this.RaisePropertyChanged("Scope");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatorSettingsData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class OperatorSettingsData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string CultureNameField;
        
        private byte LogoutOnWorkstationInactivityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CultureName
        {
            get
            {
                return this.CultureNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CultureNameField, value) != true))
                {
                    this.CultureNameField = value;
                    this.RaisePropertyChanged("CultureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte LogoutOnWorkstationInactivity
        {
            get
            {
                return this.LogoutOnWorkstationInactivityField;
            }
            set
            {
                if ((this.LogoutOnWorkstationInactivityField.Equals(value) != true))
                {
                    this.LogoutOnWorkstationInactivityField = value;
                    this.RaisePropertyChanged("LogoutOnWorkstationInactivity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.roger.pl/services", ConfigurationName="BramkiUsers.SessionManagement.ISessionManagementService")]
    public interface ISessionManagementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/services/ISessionManagementService/Connect", ReplyAction="http://www.roger.pl/services/ISessionManagementService/ConnectResponse")]
        System.Threading.Tasks.Task<System.Guid> ConnectAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/services/ISessionManagementService/Disconnect", ReplyAction="http://www.roger.pl/services/ISessionManagementService/DisconnectResponse")]
        System.Threading.Tasks.Task<bool> DisconnectAsync(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/services/ISessionManagementService/GetOperatorBySession", ReplyAction="http://www.roger.pl/services/ISessionManagementService/GetOperatorBySessionRespon" +
            "se")]
        System.Threading.Tasks.Task<BramkiUsers.SessionManagement.OperatorData> GetOperatorBySessionAsync(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/services/ISessionManagementService/GetOperatorSettingsBySessi" +
            "on", ReplyAction="http://www.roger.pl/services/ISessionManagementService/GetOperatorSettingsBySessi" +
            "onResponse")]
        System.Threading.Tasks.Task<BramkiUsers.SessionManagement.OperatorSettingsData> GetOperatorSettingsBySessionAsync(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/services/ISessionManagementService/HasPermissions", ReplyAction="http://www.roger.pl/services/ISessionManagementService/HasPermissionsResponse")]
        System.Threading.Tasks.Task<bool> HasPermissionsAsync(short systemObjectCode, short commandCode, System.Guid sessionToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISessionManagementServiceChannel : BramkiUsers.SessionManagement.ISessionManagementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SessionManagementServiceClient : System.ServiceModel.ClientBase<BramkiUsers.SessionManagement.ISessionManagementService>, BramkiUsers.SessionManagement.ISessionManagementService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SessionManagementServiceClient() : 
                base(SessionManagementServiceClient.GetDefaultBinding(), SessionManagementServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISessionManagementService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagementServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SessionManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), SessionManagementServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagementServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SessionManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagementServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SessionManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SessionManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Guid> ConnectAsync(string login, string password)
        {
            return base.Channel.ConnectAsync(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> DisconnectAsync(System.Guid sessionToken)
        {
            return base.Channel.DisconnectAsync(sessionToken);
        }
        
        public System.Threading.Tasks.Task<BramkiUsers.SessionManagement.OperatorData> GetOperatorBySessionAsync(System.Guid sessionToken)
        {
            return base.Channel.GetOperatorBySessionAsync(sessionToken);
        }
        
        public System.Threading.Tasks.Task<BramkiUsers.SessionManagement.OperatorSettingsData> GetOperatorSettingsBySessionAsync(System.Guid sessionToken)
        {
            return base.Channel.GetOperatorSettingsBySessionAsync(sessionToken);
        }
        
        public System.Threading.Tasks.Task<bool> HasPermissionsAsync(short systemObjectCode, short commandCode, System.Guid sessionToken)
        {
            return base.Channel.HasPermissionsAsync(systemObjectCode, commandCode, sessionToken);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISessionManagementService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISessionManagementService))
            {
                return new System.ServiceModel.EndpointAddress("http://127.0.0.1:8892/SessionManagement");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SessionManagementServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISessionManagementService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SessionManagementServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISessionManagementService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISessionManagementService,
        }
    }
}
