//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BramkiUsers.Communication
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LongRunningTaskLogData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class LongRunningTaskLogData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int IDField;
        
        private string MessageField;
        
        private System.DateTime TimestampField;
        
        private int TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageField, value) != true))
                {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                if ((this.TimestampField.Equals(value) != true))
                {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                if ((this.TypeField.Equals(value) != true))
                {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteAuthorizationRequestData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class RemoteAuthorizationRequestData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<int> AccessControllerIDField;
        
        private string CommentField;
        
        private System.Nullable<int> CredentialIDField;
        
        private bool DeletedField;
        
        private System.Nullable<int> EventTagField;
        
        private int IDField;
        
        private string ItemNameField;
        
        private System.Nullable<decimal> ItemUnitPriceField;
        
        private int LocationIDField;
        
        private System.Nullable<int> NumberOfItemsField;
        
        private short RequestTypeField;
        
        private System.Nullable<System.DateTime> RespondedAtField;
        
        private System.Nullable<int> RespondedByField;
        
        private string RespondedProcessField;
        
        private string SourceAddressField;
        
        private int SourcePortField;
        
        private short SourceTypeField;
        
        private byte StatusField;
        
        private System.DateTime TimestampField;
        
        private int TransactionIDField;
        
        private string UserExternalIDField;
        
        private System.Nullable<int> UserIDField;
        
        private System.Nullable<int> UserSnapshotIDField;
        
        private System.Nullable<short> UserTypeField;
        
        private System.Nullable<byte> VerificationModeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccessControllerID
        {
            get
            {
                return this.AccessControllerIDField;
            }
            set
            {
                if ((this.AccessControllerIDField.Equals(value) != true))
                {
                    this.AccessControllerIDField = value;
                    this.RaisePropertyChanged("AccessControllerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CommentField, value) != true))
                {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CredentialID
        {
            get
            {
                return this.CredentialIDField;
            }
            set
            {
                if ((this.CredentialIDField.Equals(value) != true))
                {
                    this.CredentialIDField = value;
                    this.RaisePropertyChanged("CredentialID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                if ((this.DeletedField.Equals(value) != true))
                {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EventTag
        {
            get
            {
                return this.EventTagField;
            }
            set
            {
                if ((this.EventTagField.Equals(value) != true))
                {
                    this.EventTagField = value;
                    this.RaisePropertyChanged("EventTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName
        {
            get
            {
                return this.ItemNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true))
                {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ItemUnitPrice
        {
            get
            {
                return this.ItemUnitPriceField;
            }
            set
            {
                if ((this.ItemUnitPriceField.Equals(value) != true))
                {
                    this.ItemUnitPriceField = value;
                    this.RaisePropertyChanged("ItemUnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationID
        {
            get
            {
                return this.LocationIDField;
            }
            set
            {
                if ((this.LocationIDField.Equals(value) != true))
                {
                    this.LocationIDField = value;
                    this.RaisePropertyChanged("LocationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfItems
        {
            get
            {
                return this.NumberOfItemsField;
            }
            set
            {
                if ((this.NumberOfItemsField.Equals(value) != true))
                {
                    this.NumberOfItemsField = value;
                    this.RaisePropertyChanged("NumberOfItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short RequestType
        {
            get
            {
                return this.RequestTypeField;
            }
            set
            {
                if ((this.RequestTypeField.Equals(value) != true))
                {
                    this.RequestTypeField = value;
                    this.RaisePropertyChanged("RequestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RespondedAt
        {
            get
            {
                return this.RespondedAtField;
            }
            set
            {
                if ((this.RespondedAtField.Equals(value) != true))
                {
                    this.RespondedAtField = value;
                    this.RaisePropertyChanged("RespondedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RespondedBy
        {
            get
            {
                return this.RespondedByField;
            }
            set
            {
                if ((this.RespondedByField.Equals(value) != true))
                {
                    this.RespondedByField = value;
                    this.RaisePropertyChanged("RespondedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RespondedProcess
        {
            get
            {
                return this.RespondedProcessField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RespondedProcessField, value) != true))
                {
                    this.RespondedProcessField = value;
                    this.RaisePropertyChanged("RespondedProcess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceAddress
        {
            get
            {
                return this.SourceAddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SourceAddressField, value) != true))
                {
                    this.SourceAddressField = value;
                    this.RaisePropertyChanged("SourceAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourcePort
        {
            get
            {
                return this.SourcePortField;
            }
            set
            {
                if ((this.SourcePortField.Equals(value) != true))
                {
                    this.SourcePortField = value;
                    this.RaisePropertyChanged("SourcePort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SourceType
        {
            get
            {
                return this.SourceTypeField;
            }
            set
            {
                if ((this.SourceTypeField.Equals(value) != true))
                {
                    this.SourceTypeField = value;
                    this.RaisePropertyChanged("SourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                if ((this.StatusField.Equals(value) != true))
                {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                if ((this.TimestampField.Equals(value) != true))
                {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                if ((this.TransactionIDField.Equals(value) != true))
                {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserExternalID
        {
            get
            {
                return this.UserExternalIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UserExternalIDField, value) != true))
                {
                    this.UserExternalIDField = value;
                    this.RaisePropertyChanged("UserExternalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                if ((this.UserIDField.Equals(value) != true))
                {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserSnapshotID
        {
            get
            {
                return this.UserSnapshotIDField;
            }
            set
            {
                if ((this.UserSnapshotIDField.Equals(value) != true))
                {
                    this.UserSnapshotIDField = value;
                    this.RaisePropertyChanged("UserSnapshotID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                if ((this.UserTypeField.Equals(value) != true))
                {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> VerificationMode
        {
            get
            {
                return this.VerificationModeField;
            }
            set
            {
                if ((this.VerificationModeField.Equals(value) != true))
                {
                    this.VerificationModeField = value;
                    this.RaisePropertyChanged("VerificationMode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.roger.pl/communication", ConfigurationName="BramkiUsers.Communication.ICommunicationService")]
    public interface ICommunicationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/RemoteCommand", ReplyAction="http://www.roger.pl/communication/ICommunicationService/RemoteCommandResponse")]
        System.Threading.Tasks.Task<int> RemoteCommandAsync(short objectType, int objectId, int functionCode, string functionParameterValue, bool raiseEvents, bool checkRights, bool checkObjectRights, bool checkParameterRights, int credentialId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/SetControllerDateTime", ReplyAction="http://www.roger.pl/communication/ICommunicationService/SetControllerDateTimeResp" +
            "onse")]
        System.Threading.Tasks.Task<int> SetControllerDateTimeAsync(int controllerId, System.DateTime dateTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/RunGlobalCommand", ReplyAction="http://www.roger.pl/communication/ICommunicationService/RunGlobalCommandResponse")]
        System.Threading.Tasks.Task<int> RunGlobalCommandAsync(int compositeCommandId, int credentialId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/RegisterGlobalCommand", ReplyAction="http://www.roger.pl/communication/ICommunicationService/RegisterGlobalCommandResp" +
            "onse")]
        System.Threading.Tasks.Task<int> RegisterGlobalCommandAsync(int compositeCommandId, int credentialId, System.DateTime executionTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/RunConfigurationSynchroni" +
            "zation", ReplyAction="http://www.roger.pl/communication/ICommunicationService/RunConfigurationSynchroni" +
            "zationResponse")]
        System.Threading.Tasks.Task<int> RunConfigurationSynchronizationAsync(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/RegisterConfigurationSync" +
            "hronization", ReplyAction="http://www.roger.pl/communication/ICommunicationService/RegisterConfigurationSync" +
            "hronizationResponse")]
        System.Threading.Tasks.Task<int> RegisterConfigurationSynchronizationAsync(System.DateTime executionTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GetTaskState", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GetTaskStateResponse")]
        System.Threading.Tasks.Task<int> GetTaskStateAsync(int taskId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GetTaskProgress", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GetTaskProgressResponse")]
        System.Threading.Tasks.Task<int> GetTaskProgressAsync(int taskId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GetTaskLogs", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GetTaskLogsResponse")]
        System.Threading.Tasks.Task<BramkiUsers.Communication.LongRunningTaskLogData[]> GetTaskLogsAsync(int taskId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/RunProcess", ReplyAction="http://www.roger.pl/communication/ICommunicationService/RunProcessResponse")]
        System.Threading.Tasks.Task<int> RunProcessAsync(int processId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/StopProcess", ReplyAction="http://www.roger.pl/communication/ICommunicationService/StopProcessResponse")]
        System.Threading.Tasks.Task<int> StopProcessAsync(int processId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/IsProcessActive", ReplyAction="http://www.roger.pl/communication/ICommunicationService/IsProcessActiveResponse")]
        System.Threading.Tasks.Task<int> IsProcessActiveAsync(int processId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GetLastErrorMessage", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GetLastErrorMessageRespon" +
            "se")]
        System.Threading.Tasks.Task<string> GetLastErrorMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GrantRemoteAuthorization", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GrantRemoteAuthorizationR" +
            "esponse")]
        System.Threading.Tasks.Task<bool> GrantRemoteAuthorizationAsync(int requestId, string processName, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/DenyRemoteAuthorization", ReplyAction="http://www.roger.pl/communication/ICommunicationService/DenyRemoteAuthorizationRe" +
            "sponse")]
        System.Threading.Tasks.Task<bool> DenyRemoteAuthorizationAsync(int requestId, string processName, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/TakeRemoteAuthorizationRe" +
            "questStartingFrom", ReplyAction="http://www.roger.pl/communication/ICommunicationService/TakeRemoteAuthorizationRe" +
            "questStartingFromResponse")]
        System.Threading.Tasks.Task<BramkiUsers.Communication.RemoteAuthorizationRequestData[]> TakeRemoteAuthorizationRequestStartingFromAsync(int requestId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GetRemoteAuthorizationReq" +
            "uestBetweenDates", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GetRemoteAuthorizationReq" +
            "uestBetweenDatesResponse")]
        System.Threading.Tasks.Task<BramkiUsers.Communication.RemoteAuthorizationRequestData[]> GetRemoteAuthorizationRequestBetweenDatesAsync(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GetRemoteAuthorizationReq" +
            "uestByState", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GetRemoteAuthorizationReq" +
            "uestByStateResponse")]
        System.Threading.Tasks.Task<BramkiUsers.Communication.RemoteAuthorizationRequestData[]> GetRemoteAuthorizationRequestByStateAsync(byte state, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GetLastRemoteAuthorizatio" +
            "nRequestId", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GetLastRemoteAuthorizatio" +
            "nRequestIdResponse")]
        System.Threading.Tasks.Task<int> GetLastRemoteAuthorizationRequestIdAsync(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/SetCredentialUsesRemainin" +
            "g", ReplyAction="http://www.roger.pl/communication/ICommunicationService/SetCredentialUsesRemainin" +
            "gResponse")]
        System.Threading.Tasks.Task<int> SetCredentialUsesRemainingAsync(int zoneId, int credentialId, System.Nullable<int> useRemaining, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/SetCredentialDaysRemainin" +
            "g", ReplyAction="http://www.roger.pl/communication/ICommunicationService/SetCredentialDaysRemainin" +
            "gResponse")]
        System.Threading.Tasks.Task<int> SetCredentialDaysRemainingAsync(int zoneId, int credentialId, System.Nullable<int> daysRemaining, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/SetCredentialDaysAbsentee" +
            "Time", ReplyAction="http://www.roger.pl/communication/ICommunicationService/SetCredentialDaysAbsentee" +
            "TimeResponse")]
        System.Threading.Tasks.Task<int> SetCredentialDaysAbsenteeTimeAsync(int zoneId, int credentialId, System.Nullable<int> absenteeTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GetCredentialUsesRemainin" +
            "g", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GetCredentialUsesRemainin" +
            "gResponse")]
        System.Threading.Tasks.Task<System.Nullable<int>> GetCredentialUsesRemainingAsync(int zoneId, int credentialId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GetCredentialDaysRemainin" +
            "g", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GetCredentialDaysRemainin" +
            "gResponse")]
        System.Threading.Tasks.Task<System.Nullable<int>> GetCredentialDaysRemainingAsync(int zoneId, int credentialId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/communication/ICommunicationService/GetCredentialAbsenteeTime" +
            "", ReplyAction="http://www.roger.pl/communication/ICommunicationService/GetCredentialAbsenteeTime" +
            "Response")]
        System.Threading.Tasks.Task<System.Nullable<int>> GetCredentialAbsenteeTimeAsync(int zoneId, int credentialId, System.Guid sessionToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ICommunicationServiceChannel : BramkiUsers.Communication.ICommunicationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CommunicationServiceClient : System.ServiceModel.ClientBase<BramkiUsers.Communication.ICommunicationService>, BramkiUsers.Communication.ICommunicationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CommunicationServiceClient() : 
                base(CommunicationServiceClient.GetDefaultBinding(), CommunicationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICommunicationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommunicationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CommunicationServiceClient.GetBindingForEndpoint(endpointConfiguration), CommunicationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommunicationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CommunicationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommunicationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CommunicationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommunicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> RemoteCommandAsync(short objectType, int objectId, int functionCode, string functionParameterValue, bool raiseEvents, bool checkRights, bool checkObjectRights, bool checkParameterRights, int credentialId, System.Guid sessionToken)
        {
            return base.Channel.RemoteCommandAsync(objectType, objectId, functionCode, functionParameterValue, raiseEvents, checkRights, checkObjectRights, checkParameterRights, credentialId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> SetControllerDateTimeAsync(int controllerId, System.DateTime dateTime, System.Guid sessionToken)
        {
            return base.Channel.SetControllerDateTimeAsync(controllerId, dateTime, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> RunGlobalCommandAsync(int compositeCommandId, int credentialId, System.Guid sessionToken)
        {
            return base.Channel.RunGlobalCommandAsync(compositeCommandId, credentialId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> RegisterGlobalCommandAsync(int compositeCommandId, int credentialId, System.DateTime executionTime, System.Guid sessionToken)
        {
            return base.Channel.RegisterGlobalCommandAsync(compositeCommandId, credentialId, executionTime, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> RunConfigurationSynchronizationAsync(System.Guid sessionToken)
        {
            return base.Channel.RunConfigurationSynchronizationAsync(sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> RegisterConfigurationSynchronizationAsync(System.DateTime executionTime, System.Guid sessionToken)
        {
            return base.Channel.RegisterConfigurationSynchronizationAsync(executionTime, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> GetTaskStateAsync(int taskId, System.Guid sessionToken)
        {
            return base.Channel.GetTaskStateAsync(taskId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> GetTaskProgressAsync(int taskId, System.Guid sessionToken)
        {
            return base.Channel.GetTaskProgressAsync(taskId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<BramkiUsers.Communication.LongRunningTaskLogData[]> GetTaskLogsAsync(int taskId, System.Guid sessionToken)
        {
            return base.Channel.GetTaskLogsAsync(taskId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> RunProcessAsync(int processId, System.Guid sessionToken)
        {
            return base.Channel.RunProcessAsync(processId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> StopProcessAsync(int processId, System.Guid sessionToken)
        {
            return base.Channel.StopProcessAsync(processId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> IsProcessActiveAsync(int processId, System.Guid sessionToken)
        {
            return base.Channel.IsProcessActiveAsync(processId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<string> GetLastErrorMessageAsync()
        {
            return base.Channel.GetLastErrorMessageAsync();
        }
        
        public System.Threading.Tasks.Task<bool> GrantRemoteAuthorizationAsync(int requestId, string processName, System.Guid sessionToken)
        {
            return base.Channel.GrantRemoteAuthorizationAsync(requestId, processName, sessionToken);
        }
        
        public System.Threading.Tasks.Task<bool> DenyRemoteAuthorizationAsync(int requestId, string processName, System.Guid sessionToken)
        {
            return base.Channel.DenyRemoteAuthorizationAsync(requestId, processName, sessionToken);
        }
        
        public System.Threading.Tasks.Task<BramkiUsers.Communication.RemoteAuthorizationRequestData[]> TakeRemoteAuthorizationRequestStartingFromAsync(int requestId, System.Guid sessionToken)
        {
            return base.Channel.TakeRemoteAuthorizationRequestStartingFromAsync(requestId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<BramkiUsers.Communication.RemoteAuthorizationRequestData[]> GetRemoteAuthorizationRequestBetweenDatesAsync(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken)
        {
            return base.Channel.GetRemoteAuthorizationRequestBetweenDatesAsync(startDateTime, endDateTime, sessionToken);
        }
        
        public System.Threading.Tasks.Task<BramkiUsers.Communication.RemoteAuthorizationRequestData[]> GetRemoteAuthorizationRequestByStateAsync(byte state, System.Guid sessionToken)
        {
            return base.Channel.GetRemoteAuthorizationRequestByStateAsync(state, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> GetLastRemoteAuthorizationRequestIdAsync(System.Guid sessionToken)
        {
            return base.Channel.GetLastRemoteAuthorizationRequestIdAsync(sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> SetCredentialUsesRemainingAsync(int zoneId, int credentialId, System.Nullable<int> useRemaining, System.Guid sessionToken)
        {
            return base.Channel.SetCredentialUsesRemainingAsync(zoneId, credentialId, useRemaining, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> SetCredentialDaysRemainingAsync(int zoneId, int credentialId, System.Nullable<int> daysRemaining, System.Guid sessionToken)
        {
            return base.Channel.SetCredentialDaysRemainingAsync(zoneId, credentialId, daysRemaining, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> SetCredentialDaysAbsenteeTimeAsync(int zoneId, int credentialId, System.Nullable<int> absenteeTime, System.Guid sessionToken)
        {
            return base.Channel.SetCredentialDaysAbsenteeTimeAsync(zoneId, credentialId, absenteeTime, sessionToken);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> GetCredentialUsesRemainingAsync(int zoneId, int credentialId, System.Guid sessionToken)
        {
            return base.Channel.GetCredentialUsesRemainingAsync(zoneId, credentialId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> GetCredentialDaysRemainingAsync(int zoneId, int credentialId, System.Guid sessionToken)
        {
            return base.Channel.GetCredentialDaysRemainingAsync(zoneId, credentialId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> GetCredentialAbsenteeTimeAsync(int zoneId, int credentialId, System.Guid sessionToken)
        {
            return base.Channel.GetCredentialAbsenteeTimeAsync(zoneId, credentialId, sessionToken);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICommunicationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICommunicationService))
            {
                return new System.ServiceModel.EndpointAddress("http://127.0.0.1:8892/Communication");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CommunicationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICommunicationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CommunicationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICommunicationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICommunicationService,
        }
    }
}
